### ISSUE TITLE
Table row colour scheme

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs-site#10]
The alternating row colours in tables (particularly viewable in the recommended-products page) strongly do not fit with the colour scheme. This is currently an opinion rather than a requirement, but it's probably worth getting in touch with marketing or ux to sign off on some of these decisions and/or open input from their perspective.

**Comment by jeremyw24** [comment]
@mghill can I have an update on this issue, please close if no longer relevant.

**Comment by mghill** [comment]
It's just sitting there as very low priority, once the mvp is up was planning on running it past Jordy/Candy for any design related input
