### ISSUE TITLE
Docs Site mirror (?) for Public & Partner versions

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs-site#11]
In some way segregate the docs site so that there is one region for high-level public facing documentation, and one region for more technical docs as required by partners etc. Content should be able to be displayed on either or both. Some parts will need clarity on what goes where, but generally the public facing section is (entirely?) a subset of the partner section.

**Comment by kimburgess** [comment]
A [config item](https://github.com/PlaceOS/docs-site/blob/487b7f75c39d43daee9ce81a0024e227750d745e/package.json#L15) exists for specifying where the doc content is defined. Using this it is possible to build multiple versions of the site with different content sets. A nice extension of this may be to use an upstream gateway that then transparently serves the appropriate build based on the presence of an auth session.

Any non-public content should be authored is a repository seperate to PlaceOS/docs. There will be a need to define how these merge, however that is a sub-problem that can be solved when this is implemented.

From the docs-site context, yes support for this is already built in and ready to go.

**Comment by mghill** [comment]
That's reassuring, and a pretty straightforward solution. When/if needed, spinning up an internal-docs (partner-docs, whatever) repo is a relatively easy thing to do, given the support is already there.
