### ISSUE TITLE
Table dimensions

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs-site#22]
Low priority, just a note to record:
Markdown tables are auto formatted by docusaurus. Sometimes this can result in unusual column width choices (i.e. even column width despite hugely different amounts of content) etc.

There is probably a way to manage this with js or html, but didn't want to get too into it at the moment as it could get messy fast.

**Comment by jeremyw24** [comment]
@mghill can I have an update on this issue, please close if no longer relevant.

**Comment by mghill** [comment]
This is also a @kimburgess one (looks like I cannot edit as I'm not an owner of docs-site repo). Not sure how important it is (not very) and is just logged for reference if it becomes an issue worth addressing. Layout & styling are not currently a high priority

**Comment by kimburgess** [comment]
@mghill can you confirm if this is still occurring based on current state of the site?

If so, can you please provide a link to some content where this is visible.

**Comment by mghill** [comment]
It's there, see https://docs-placeos.vercel.app/reference/recommended-products
If you look at that first table, 
![image](https://user-images.githubusercontent.com/14900157/118204332-585a9d80-b4a1-11eb-952e-3163595bc7db.png)
an example would be how "Information Kiosks" flows over two lines. I feel like if this was a table in a word document, a human doing layout would fiddle with the column width so that it was one line.

I definitely rate this as a low-priority "nice to have" feature. It is a formatting preference, tables etc are still very much useable

**Comment by kimburgess** [comment]
Looking at the [markdown source behind that example](https://github.com/PlaceOS/docs/commit/9d45002d2b56f8be0d4c7866cb59dcc11362804f#diff-2ea37a333a9ddaee0421133d2c8d4a0a1e6f7766389e064fce3354357524275fR17-R21), there's a bit of explicit layout (`<br>` tags) that is influencing this. With those removed, this becomes much neater:
![2D244BCE-8D90-4717-8D21-A2C03C221794](https://user-images.githubusercontent.com/843652/118210705-2e5ba800-b4ae-11eb-9284-bf68be5f840b.jpeg)

One thing that you may note is that model number which is now wrapping on the hyphen. Terms like this where the full item is a single semantic element are worth writing with a non-breaking hyphen (`&#8209;`) or non-breaking space (`&nbsp;`). This will encode this properly and ensure correct presentation everywhere.
![F633CD83-E40C-4BD9-BF11-472AB1D63172](https://user-images.githubusercontent.com/843652/118211052-d6717100-b4ae-11eb-84fc-67d4897f5f1b.jpeg)

It is also worth remembering that tables are a semantic element for presenting tabular information. If there is a hard requirement to present content with a very specific visual layout, [other tools exist for this](https://infima.dev/docs/layout/grid). However in the interest of keeping clean separation between content and presentation, usage of that would be good to minimise.

With the above, I'll close this with no action. However if there are requirements here that I'm missing, happy to be disputed, reopen and discuss further.
