### ISSUE TITLE
Auto Generated ToC is using full title text and not {#heading-id}

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs-site#25]
**Describe the bug**
The right hand sidebar with an autogenerated table of contents (derived from the level 2&3 headers) uses the full text of those headers when it should use the provided abbreviation

**Your environment**
Tested in local version of docs-site deployment, but is also the case in vercel deployments (see https://docs-39ww2eknk-placeos.vercel.app/reference/system-architecture#HADC)

**To Reproduce**
Set any custom ID for a header by appending {#custom-id} to the line

**Expected behavior**
In the screenshot below, the URL shows the short version (#VPC), in the main body you can see the full text, "VPC Architecture: `vpc.yml`" and in the table of contents on the right you can see this duplicated in red, in full. 

**Screenshots**
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/14900157/116170017-49f24f00-a749-11eb-9334-277304c72321.png">

**Additional context**
This isn't critical by any stretch. I'm not even 100% certain it's a bug, rather than a proposed extension.

**Comment by kimburgess** [comment]
Resolved via 8da7821b01e4dc8deaba89c02cc0e67dd21aa33d.

**Comment by mghill** [comment]
@kimburgess  Looking at both [this change](https://docs-site-8mi0s9m01-placeos.vercel.app/how-to/fargate-modular) and the generic https://docs.placeos.vercel.app/how-to/fargate-modular today, I can't see any differences on this topic?

**Comment by kimburgess** [comment]
I may have misinterpreted the original issue. What do you expect to see in that right side nav?

**Comment by mghill** [comment]
I had thought the abbreviated {#header-id}. But I assumed there would be discussion on the issue because those aren't necessarily the best option. Could be something like a truncated title (say, ignoring anything after a colon). 
What was the change that went in here?

**Comment by kimburgess** [comment]
There was some issue with the assignment of explicit heading ID's in an earlier version. I misread this issue relating to that.

To confirm, current behaviour is working as per design. When [setting a heading id](https://docusaurus.io/docs/markdown-features/headings#explicit-ids) this value is the anchor link only (what appears in the URL hash fragment). The TOC displays the heading as written, but links to this explicit id.

**Comment by mghill** [comment]
Yeah, I suspected this was currently working per spec rather than a bug, and mentioned as much. I kind of want descriptive titles but tidy ToCs, but the solution here is probably just snappier titles in the first place
