### ISSUE TITLE
Content in readme files not rendered

### ISSUE THREAD

**Issue by mghill** [PlaceOS/docs-site#5]
Vercel doesn't pick up readme.md as the default for a directory. Needs either something like `index.html` or possibly something like a file named the same as the directory. 
@KimBurgess I'm unclear whether vercel is only used for staging (so this isn't a Real Issue^tm ) or if it is involved in actual deployment with docusaurus

https://vercel.com/docs/directory-listing

ref: https://v2.docusaurus.io/docs/2.0.0-alpha.69/docs-introduction/#home-page-docs

**Comment by kimburgess** [comment]
Just ran a quick test - for items not in the root (everything but initial landing page `/`) something that works today is to place the index page in the parent directory, with the same name as the directory it is for.

```
docs/
├─ foo/
│  ├─ a.md        <--- this will render to /foo/a
│  ├─ b.md
│  ├─ c.md
├─ foo.md         <--- this will render to /foo/
├─ README.md      <--- only shows in GitHub and as part of the content repo
```

Personally I think this is a rather neat approach. _If_ there are issues with this though, it looks like using `index.md` as the naming from these seems to be the common setup (https://github.com/facebook/docusaurus/issues/2537).

I'll close this now with the above options in place but please feel free to reopen if I'm missing anything.

**Comment by mghill** [comment]
Yep, I'd meant to expand on OP after tossing in the docusaurus link, but basically agree on the conclusions in your last comment. I totally get the use of ReadMe as a meta-document, and it should remain behind the scenes. 
I *kind of* prefer to have all Foo content in the Foo folder, and manually set the slug to `/` (and by convention name it foo.md). 
Only other consideration on this would be about how this doc structure manifests in the auto-generated sidebar/contents situation. If either solution works better there, then happy to do that.

**Comment by mghill** [comment]
Not sure if this is a versioning thing (or if I have misunderstood implementation this), but in current tests neither the above solution (intentional conflict doc & path naming) nor the linked index concept work, despite it [now being in official documentation](https://v2.docusaurus.io/docs/creating-pages#routing), though it only works for js pages, not md.

Edit: the above works in terms of URLs, but the sidebar is a mess
