### ISSUE TITLE
Provide the ability to hide content from the sidebar

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/docs-site#8]
Add support for the following frontmatter:
- [ ] `sidebar_hide`: exclude the doc from sidebar listing
- [ ] `sidebar_category_hide`: exclude the full category from sidebar listing

Note: if all content is hidden, the category should also hide.

**Comment by mghill** [comment]
relatedly, documentation for the existing [sidebar features](https://github.com/PlaceOS/docs-site/blob/810bc2f70123028f6cfe14ce918090050bc4d3a7/sidebars.js#L1-L16) commented in the sidebar.js file itself.

Just noting here for reference

**Comment by mghill** [comment]
can you pop the new implemented frontmatter into the readme where it goes through the options & defaults? Just to keep it in one place
